[build]
command = "yarn build"
publish = "public"

[functions]
directory = "netlify/functions"

[functions.graphql]
included_files = [
    ".cache/data/**",
    ".cache/query-engine/**",
    "node_modules/gatsby-graphiql-explorer/index.html",
    "node_modules/gatsby-graphiql-explorer/app.js",
]
external_node_modules = ["msgpackr-extract"]
node_bundler = "esbuild"

[[redirects]]
from = "/___graphql*"
to = "/.netlify/functions/graphql"
status = 200

[[redirects]]
from = "/___graphiql*"
to = "/.netlify/functions/graphql"
status = 200

[[redirects]]
from = "/products/"
to = "/.netlify/functions/__ssr"
status = 200

[[redirects]]
from = "/products/:slug"
to = "/.netlify/functions/__ssr"
status = 200

[[redirects]]
from = "/page-data/products/page-data.json"
to = "/.netlify/functions/__ssr"
status = 200

[[redirects]]
from = "/page-data/products/:slug/page-data.json"
to = "/.netlify/functions/__ssr"
status = 200

[dev]
# So it doesn't run gatsby develop
framework = "#static"

[[plugins]]
package = "@netlify/plugin-gatsby"
