[build]
command = "GATSBY_EXPERIMENTAL_GENERATE_ENGINES=1 yarn build"
publish = "public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[functions.dsr]
included_files = [
    ".cache/data/**",
    ".cache/query-engine/**",
    ".cache/page-ssr/**",
    "node_modules/msgpackr-extract/**"
]

[functions.graphql]
included_files = [
    ".cache/data/**",
    ".cache/query-engine/**",
    "node_modules/gatsby-graphiql-explorer/index.html",
    "node_modules/gatsby-graphiql-explorer/app.js",
    "node_modules/msgpackr-extract/**"
]

[[redirects]]
from = "/___graphql*"
to = "/.netlify/functions/graphql"
status = 200

[[redirects]]
from = "/___graphiql*"
to = "/.netlify/functions/graphql"
status = 200

[[redirects]]
from = "/*"
to = "/.netlify/functions/dsr"
status = 200

[dev]
# So it doesn't run gatsby develop
framework = "#static"

[[plugins]]
package = "./plugin"
